---
- name: Deploying with Kubernetes
  hosts: localhost
  tasks:

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/secret.yaml') | from_yaml }}"

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/backend.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/frontend.yaml') | from_yaml }}" 