---
- name: Deploying with Kubernetes
  hosts: localhost
  tasks:

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 

    - name: Get list of namespaces using k8s module with custom kube-config file
      k8s_info:
        kind: NamespaceList
        kubeconfig: /home/rizwan/.kube/config
      register: namespaces

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/secret.yaml') | from_yaml }}"

    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/backend.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes/frontend.yaml') | from_yaml }}" 