apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pms-server
  template:
    metadata:
      labels:
        app: pms-server
    spec:
      containers:
        - name: pms-server
          image: rizwans21/pms_server
          ports:
            - name: http
              containerPort: 3001
          env:
          - name: CONNECTION_URL
            valueFrom:
              secretKeyRef:
                name: secret
                key: connection-url
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: secret
                key: port
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: jwt-secret