apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pms_server
  template:
    metadata:
      labels:
        app: pms_server
    spec:
      containers:
        - name: pms_server
          image: pratyush02/pms_server
          ports:
            - name: http
              containerPort: 3001
          env:
          - name: CONNECTION_URL
            valueFrom:
              secretKeyRef:
                name: secret
                key: connection-url
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: secret
                key: port
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: jwt-secret
                
---
apiVersion: v1
kind: Service
metadata:
  name: pms_server-service
spec:
  selector:
    app: pms_server
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
      # nodePort: 30001