apiVersion: v1
kind: Service
metadata:
  name: pms-client-service

spec:
  type: LoadBalancer
  selector:
    app: pms-client
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      # nodePort: 30000