apiVersion: v1
kind: Secret
metadata:
  name: 
type: Opaque
data:
  port: MzAwMQ==
  connection-url: bW9uZ29kYitzcnY6Ly9tZXJuOm1lcm5AY2x1c3RlcjAua2RoeXAubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  jwt-secret: Ymlub2Q=
